# Generated by Django 5.2.6 on 2026-06-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0002_user_username_candidate_employer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='candidate',
        ),
        migrations.AlterModelTable(
            name='employer',
            table='employer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
