# Generated by Django 5.2.6 on 2026-06-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0003_alter_user_options_alter_candidate_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='certifications',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('credential_url', models.URLField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='candidate/certifications/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='ai_resume_building.candidate')),
            ],
            options={
                'db_table': 'certification',
                'ordering': ['-created_at'],
            },
        ),
    ]
